### ISSUE TITLE
Typescript compilation with latest version 

### ISSUE THREAD

**Issue by nouman91** [micromark/micromark-extension-gfm-strikethrough#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.0.7

### Steps to reproduce

Install the latest version

### Expected behavior

It should run fine there should not be any issues while building the project

### Actual behavior

I had some dependency issues so I deleted the yarn.lock file and re-installed everything, but some of the packages depend internally on this package, and since deleting yarn.lock file caused the internal packages to go to the latest version in this case from 1.0.1 to 1.0.7 and it started to fail the build of the project. Here are the errors I am getting. 

```
"../../node_modules/micromark-extension-gfm-footnote/index.d.ts(5,8): error TS1005: ',' expected.\n" +
    "../../node_modules/micromark-extension-gfm-footnote/index.d.ts(6,8): error TS1005: ',' expected.\n" +
    "../../node_modules/micromark-extension-gfm-strikethrough/index.d.ts(2,32): error TS1005: ',' expected
```

While I know this is a bit cryptic but since you released the 1.0.7 just today can you check why its happening? 

The dependency which is causing the issue:
remark-gfm@3.0.1#micromark-extension-gfm@2.0.3#micromark-extension-gfm-strikethrough@1.0.7

### Runtime

Node v14

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
My guess is you have an ancient typescript version. What's it? Please update that

**Comment by nouman91** [comment]
I have fairly latest one, I am using 4.2.4

**Comment by ChristianMurphy** [comment]
Latest TypeScript is version 5

**Comment by nouman91** [comment]
Yeah, I know and I am not saying I have the latest one I am saying I have the fairly latest one. 
@wooorm which version should I be using if 4.2.4 is not compatible?

**Comment by ChristianMurphy** [comment]
I understand you now.
I was getting confused by the use of "fairly latest" which is a contradiction.
"latest" is only the most recent, "fairly" is not the most recent.

> version should I be using if 4.2.4 is not compatible?

This package, and most of unified is tested against TypeScript 5, try that first.
https://github.com/micromark/micromark-extension-gfm-strikethrough/blob/b8c00a3164ee6e0dbadf65e8e14f6137e0345a07/package.json#L62

That said, the specific feature you are seeing an error on was added in TypeScript 4.5 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names
You could upgrade to that, if you aren't ready to use the latest major of TS.

**Comment by ChristianMurphy** [comment]
Adding on, TypeScript 4.5 was release 2 years ago https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/
TypeScript 4.2 is rather outdated.

**Comment by remcohaszing** [comment]
I think it’s good to follow the [DefinitelyTyped support window](https://github.com/DefinitelyTyped/DefinitelyTyped#support-window) of 2 years. TypeScript 4.3 is being dropped this month.

**Comment by nouman91** [comment]
Thank you, guys, thank you @ChristianMurphy I upgraded to typescript version 4.5.5 it fixed my problem, but now onto fixing material-ui issues :(
